andela/andela-societies-frontend

- package.json
- server.js
- yarn.lock
Resolves #8 
This PR removes pug. Its an unused package 
I ran `yarn remove pug` and removed the reference to pug as a view engine in the express app.
Run `yarn deploy` and make sure there are no error messages in the console when you open the app in the browser.
> Resolves #8  - remove unused packages

- src/containers/Router.jsx
- tests/containers/Router.test.jsx
**Description**
The `BrowserRouter` Component does not accept more than one child. This causes the app to throw an error.
**Fix**
Add Switch as the only child of  `BrowserRouter` component.
**How to test**
While in root folder of the project, run:
- `git pull`
- `git checkout fix-35-fix-bug-in-router`
- `yarn start`
Make sure the sign in page shows and there are no errors in the console related to `BrowesrRouter`.
> Resolves #35 - Fix bug in router

- src/containers/Page.jsx
- src/containers/SignIn.jsx
**Description**
When an unauthenticated user attempts to access a protected route and are redirected to the Sign in page, they should see a notification stating `You must sign in with an Andela account`
**How to Test**
Ensure you are logged out of your Andela account. Then try accessing the /my-activities page directly by typing in the path in the browser url bar. You should be redirected to the Signin page and see the `You must sign in with an Andela account` notification.
> [#156034201] Display notification on the Sign in page when user is redirected from protected route

- README.md
- package.json
- yarn.lock
**Description**
Fix deployment errors caused by installing packages using `npm` instead of `yarn`.
**Fix**
I ran `yarn install`. This updated the `yarn.lock` file. 
I also added a notice in the README.md file to (hopefully) prevent this in future.
> Resolves #61 -  Fix deployment errors

- src/assets/scss/ActivityCard.scss
- src/assets/scss/MasonryLayout.scss
- src/components/TruncateDescription.jsx
- src/components/activities/ActivityCard.jsx
- src/containers/MasonryLayout.jsx
- src/containers/VerifyActivities.jsx
- src/fixtures/activity.js
- tests/components/TruncateDescription.test.jsx
- tests/components/activities/ActivityCard.test.jsx
Fixes the bug with the display of activity cards from Top to Bottom and have the card width spanning according to the text description. 
* Have cards flowing from left to right
* Modify height of cards to make them equal
* Create a method to have the description shortened to fit the height of the card.
* Have view more and less functionality for cards with long description
`git clone` this repo or pull this branch, `cd` into `andela-societies-frontend`, `yarn install`. Navigate to `My Activities` or `Verify activities`.
[157116995](https://www.pivotaltracker.com/story/show/157116995)
> #[157116995] Rework display of activity cards

- src/components/routes/PrivateRoute.jsx
- src/components/sidebar/Sidebar.jsx
- src/constants/roles.js
- src/containers/Page.jsx
- src/containers/Router.jsx
- src/fixtures/store.js
- src/fixtures/userProfile.js
- src/helpers/authentication.js
- src/helpers/pageInfo.js
- src/reducers/initialState.js
- tests/components/routes/PrivateRoute.test.jsx
- tests/containers/Page.test.jsx
- tests/containers/Router.test.jsx
[Pivotal Tracker story](https://www.pivotaltracker.com/story/show/158591325)
This PR adds functionality to ensure that pages such as verify activities and redemptions page are only accessed by users with the required roles
- `/verify-activities` should only be accessed by users with **secretary**, **success** or **success ops** roles
- `/redemptions` should only be accessed by users with **president**, **success** or **success ops** roles
- Any attempt to access the protected routes by users without the required roles should redirect them to the home page `/`
> Resolves[158591325] protect routes by user roles

- src/containers/VerifyActivities.jsx
- src/helpers/index.js
- tests/containers/VerifyActivities.test.jsx
[Pivotal Tracker Story](https://www.pivotaltracker.com/story/show/158792989)
Currently, when a Success Ops user logs in and navigates to verified activities, he/she cannot approve activities. This PR introduces a fix for that.
- I have changed the Button's props back to an onClick props as opposed to handleClick props which were introduced through #87. Changing this has introduced conflicts to the codebase and so to keep consistency and resolve the current bugs with the buttons.
- The Verify component has also been integrated with the snack bar so it returns errors if the approve button is clicked and no activities are elected
> Resolves #158792989 Fix the Component that verifies activities for success ops users

- src/assets/scss/Loader.scss
- src/assets/scss/style.scss
- src/components/header/Breadcrumb.jsx
- src/components/loaders/Loader.jsx
- src/components/sidebar/Sidebar.jsx
- src/constants/roles.js
- src/containers/Home.jsx
- src/containers/MyActivities.jsx
- src/containers/Page.jsx
- src/containers/Redemptions.jsx
- src/containers/SignIn.jsx
- src/containers/VerifyActivities.jsx
- src/helpers/pageInfo.js
- tests/components/header/Header.test.jsx
- tests/components/sidebar/Sidebar.test.jsx
- tests/containers/Home.test.jsx
- tests/containers/MyActivities.test.jsx
- tests/containers/Redemptions.test.jsx
- tests/containers/VerifyActivities.test.jsx
Replace MyActivities page as the home page by adding a homepage component that serves as a loading screen when a user logs in before being navigated to restricted pages once user roles have been fetched from the API. 
Once logged in, you should see a loading page before being redirected
Redirect logic according to role:
- Fellow/society secretary/society president -> MyActivities page 
- Success ops -> VerifyActivities page 
- CIO -> Redemptions page
> [Feature] add a home page to act as a loading screen

- src/components/sidebar/Stats.jsx
- src/containers/MyActivities.jsx
- src/containers/Redemptions.jsx
- src/containers/VerifyActivities.jsx
- src/helpers/statsGenerator.js
- tests/containers/Redemptions.test.jsx
- tests/helpers/statsGenerator.test.js
Have the Stats component display relevant stats for each page. The stats and pages referred to here are the number of activities/ redemptions and points associated with `Home`, `Verify activities`, `Redemption` pages.
Once you login to the application, the information displayed on the top right should conform to the number of activities and points on that page you're on.
[As logged in user, I should see relevant stats displayed on the stats component for each page](https://www.pivotaltracker.com/story/show/158936624)
> Have the stats component display relevant stats for each page

- config.js
- src/containers/Redemptions.jsx
Have the stats component display appropriate stats on Redemptions page when logged in as a `society president`
Once you login to the application, i.e. as a `society president`, while on the `Redemptions page` the `Pending redemptions` and `Total points` should be equal to the number of activities and points on that page.
[Fixes showing relevant details on the stats component on the Redemptions page when logged in as a society president.](https://www.pivotaltracker.com/story/show/159036599)
> [159036599] Fixes displaying appropriate stats on Redemptions page when logged in as society president

- src/assets/scss/FormField.scss
- src/containers/forms/LogActivityForm.jsx
- src/fixtures/categories.js
- src/fixtures/labels.js
- tests/containers/forms/LogActivityForm.test.jsx
[Pivotal Tracker Story](https://www.pivotaltracker.com/story/show/158124097)
Currently, when society members selects `Bootcamp interviews` as an activity category, they do not have access to an input field to enter the number of interviewees. This PR fixes that.
Display a input field to for number of interviewees when the `Bootcamp interviews` category is selected
You should see the `# of interviewees` field when `Bootcamp interviews` is selected as the category
> Resolves #158124097 Conditionally display input field on the log activity form

- tests/components/activities/ActivityCard.test.jsx
This PR display the view for the verified Activities from societies in **pending** state that need to be verified by a success op team member.  This also displays activities that are **in review** for the individual social secretaries for each society so they can approve them ready for the success-op team.
Once logged in as either a social secretary or a success op member
Navigate to Verify Activities tab on the Sidebar
- You should view a list of activities in either pending state for all societies or in review for social secretaries.
**Success-Op user view**
**Social Secretary user view**
>  #158894695 Display View for Verify Activities For Success Op Users & Social Secretaries

- src/containers/Home.jsx
- src/containers/MyActivities.jsx
- src/containers/Society.jsx
- src/fixtures/store.js
- tests/containers/SignIn.test.jsx
- tests/reducers/allActivitiesReducer.test.js
- tests/reducers/commentsReducer.test.js
- tests/reducers/myActivitiesReducer.test.js
Adds loader to the society page.
When a user visits the society page, a loader should be displayed before activities are fully populated to the page.
N/A
[159430139](https://www.pivotaltracker.com/story/show/159430139)
N/A
N/A
What does this PR do?
Refactors URLs for the services to review, approve, reject logged activities by a society secretary or success ops member
> Add loader to society page

- src/components/header/PageHeader.jsx
- src/containers/Redemptions.jsx
- src/fixtures/redemptions.js
- tests/components/header/PageHeader.test.jsx
- tests/containers/Redemptions.test.jsx
Fixes the bug on successful loading of the redemptions page, it displays redemptions for all societies.
On successful loading of the redemptions page, it displays redemptions belonging to president's society.
* Filter redemptions based on the president's society.
* Filter redemptions based on the selected society in the navigation tabs when logged in as a success ops member or CIO.
* Modify `filterRedemptions` function to be used by the PageHeader to filter redemptions based on a status
[159518063](https://www.pivotaltracker.com/story/show/159518063)
> Fixes bug when displaying redemptions when logged in as a president's society

- src/actions/verifyActivityActions.js
- src/components/notifications/SnackBar.jsx
- src/constants/snackbarTimeout.js
- src/containers/Page.jsx
- src/containers/forms/CommentsForm.jsx
- src/containers/forms/RedeemPointsForm.jsx
- tests/actions/verifyActivityActions.test.js
On successful creation of a redemption, the redeem points modal shows a message i.e. success or error message, before closing the modal.
Add the timeout used to call the `handleCloseModal ` function
[159517835](https://www.pivotaltracker.com/story/show/159517835)
> Fixes success/error messages showing when using RedeemPoints form

- src/containers/Redemptions.jsx
Displays name for stats on redemption page according to filtered redemptions status.
As a society president, success OPS or CIO when I am on the redemptions page and I filter redemptions. 
The stats title should tally with the filtered redemption status.
[159518152](https://www.pivotaltracker.com/story/show/159518152)
> Display name for stats on redemption page according to filtered redemptions status

- src/assets/scss/ProfileDisplay.scss
- src/containers/Society.jsx
Fixes bugs to have activity cards display description and date which the activity was logged. Also,  make the details of logged in user, visible under the profile section in society pages.
Passed down `activityDate` and `description` prop to ActivityCards component.
Add `color` property to `.profileDisplay` class.
[159695959](https://www.pivotaltracker.com/story/show/159695959)
> #159695959  Fix display of activity description, date of logged activity and user profile details.

- src/actions/allActivitiesActions.js
- src/containers/MyActivities.jsx
- src/containers/VerifyActivities.jsx
- tests/actions/allActivitiesActions.test.js
- tests/containers/MyActivities.test.jsx
- tests/containers/VerifyActivities.test.jsx
Displays activities logged for a specific society on VerifyActivities page for verification by society secretary.
Below are steps taken to have logged activities displayed on VerifyActivities page
* change URL in `fetchAllActivities` thunk to `/logged-activities?paginate=false`
* change date prop in ActivityCard to `activityDate`
[#159763170](https://www.pivotaltracker.com/story/show/159763170)
> Display activities logged on VerifyActivities page for verification.

- src/common/DateField.jsx
- src/components/activities/ActivityCard.jsx
- src/components/notifications/SnackBar.jsx
- src/constants/dataFormats.js
- src/constants/snackbarTimeout.js
- tests/common/DateField.test.jsx
* Adjust validity period on Date picker for activity to be logged
* Update the SnackBar timeout Duration to 500ms
* Fix TruncateDescription in ActivityCard
* Logging of activities should be possible for activities that happened up to 30 days ago. They are currently set to just the beginning of the month at the time of the logging. This PR adjusts the DatePicker valid window for up to a month back
* The SnackBar duration on success is changed from a full 3 seconds! to a manageable half a second
* The TruncateDescription module is only called if the description _is not null_
We are using moments to adjust this.
The native date input field doesn't support opening the caret when the input field is clicked. The alternative is to build a custom date picker which isn't a priority for now. We are …
> Fix DatePicker, SnackBar Duration, Null description error

- src/assets/scss/FormField.scss
- src/containers/forms/CreateCategoryForm.jsx
- tests/containers/forms/CreateCategoryForm.test.jsx
Adds option to specify categories that support multiple participants
Introduces form field in create category modal to allow Success Ops member to specify support for multiple participants. This value is registered as a boolean value.
[159956751](https://www.pivotaltracker.com/n/projects/2154966/stories/159956751)
> Add support for Multiple Participants

- src/containers/Redemptions.jsx
- tests/containers/Redemptions.test.jsx
Displays redemptions with the status of `completed`
* Add a check for the role of `finance`
* Filter redemptions by status `completed` 
* Set selected status to be `completed`
* Modified filter in `handleChangeTab ` to check the role of finance and then filter by completed status
[160583562](https://www.pivotaltracker.com/story/show/160583562)
> Fix bug to filter redemptions by completed status when role is finance

- src/containers/Page.jsx
Removes the modal button from the Society View.
- Add a regex to prevent all Society urls (/society/...) from having the modal button rendered on them.
> #161249824 Remove modal button from Society view

- src/assets/scss/Header.scss
- src/helpers/pageInfo.js
It prevents the success-ops user from having access to the redemptions view.
Remove the `Success-ops` role for redemptions in the `PageInfo` object.
> #160618987 Remove SUCCESS OPS rights to Redemptions View

- src/assets/scss/_pageNotFound.scss
- src/assets/scss/style.scss
- src/containers/PageNotFound.jsx
- src/containers/Router.jsx
- tests/containers/PageNotFound.test.jsx
It directs users to a 404 page when they try to or mistakenly access invalid routes.
- Created a `PageNotFound` component for the feature and styled it appropriately.
- All invalid routes redirect to the `PageNotFound` component.
`#61482151`
>  Creation of a 404 page for invalid routes.

- .circleci/config.yml
- scripts/slack_notification.sh
This Pull Request introduces notifications that will be specifically triggered when a deployment is made on Github by a push on either the master or develop branch.
The task involves notifying the developers in the team and the TTL once a successful deployment has been made to production or staging or if a failure occurred during deployment. 
None
https://www.pivotaltracker.com/story/show/161539722
None
A sample of the messages that will be sent to the slack channel after a production deployment, both success and failure.
A sample of the messages that will be sent to the slack channel after a staging deployment, both success and failure. Ignore the branch name in this screenshot.
> #161539722 Send customised notifications for develop and master builds

- config.js
Updates the staging_v2 and production_v2 environment URLs.
The domain design-societies.andela.com was chosen as the staging_v2 environment URL. To make the domains tailored to the staging_v2 and production_v2 environment names I changed the URLs to staging-v2-societies.andela.com and api-staging-v2-societies.andela.com for the staging_v2 environment and societies-v2.andela.com and societies-api-v2.andela.com for the production_v2 environment. Once our MVP2 is done the main URL societies.andela.com will be mapped to the Kubernetes service that is running the production_v2 environment. This provides the ability for a Blue-Green Deployment environment.
This P.R. goes hand in hand with [this](https://github.com/andela/bench-products-infrastructure/pull/58) …
> #163632873 Update domains on Andela Societies for MVP2

- src/app/Authentication/components/AuthenticateRoute.js
- src/app/Sidebar/components/SidebarContainer.js
- src/app/Sidebar/components/tests/SidebarContainer.test.js
Fixes the bug to avail `userId` at all times to `fetchUserRole `.
> Avail userId to fetchUserRole

- src/app/Authentication/components/AuthenticateRoute.js
- src/app/Dashboard/components/MyActivitiesComponent.js
- src/app/Sidebar/components/SidebarContainer.js
- src/app/Sidebar/components/tests/SidebarContainer.test.js
- src/app/Societies/components/SocietyActivitiesComponent.js
- src/app/VerifyActivities/components/VerifyActivitiesComponent.js
> Fix the Activity category and Date display
