andela/andela-societies-frontend

- .circleci/config.yml
- README.md
- package.json
- yarn.lock
This PR integrates Circle CI to the project.
> #154728335 Add circleCI integration

- Procfile
- app.json
- package.json
- webpack.config.prod.js
This PR adds configurations and setups needed to deploy the app to Heroku.
- Add Procfile
- Move `html-webpack-plugin` to dependencies in package.json
[#154728500](https://www.pivotaltracker.com/story/show/154728500)
> #154728500 Setup Heroku deployment

- src/components/App.jsx
- src/components/activities/ActivityCard.jsx
- src/components/header/Breadcrumb.jsx
- src/components/header/Header.jsx
- src/components/header/Notification.jsx
- src/components/header/NotificationList.jsx
- src/components/header/PageHeader.jsx
- src/components/header/ProfileDisplay.jsx
- src/components/sidebar/Sidebar.jsx
- src/containers/MasonryLayout.jsx
- src/containers/MyActivities.jsx
- src/index.jsx
- tests/containers/MasonryLayout.test.jsx
Resolves #17 
Add missing code comments
N/A
N/A
Check #19 for commentary on resolving this ticket. Wiki to be created soon
> Resolves #17 - add comments to code

- src/assets/scss/Stats.scss
- src/assets/scss/style.scss
- src/components/App.jsx
- src/components/sidebar/Stats.jsx
- tests/components/sidebar/Stats.test.jsx
**Description:**
Create Stats component
**Screenshot:** 
**How to test**
- Run
```
$ git pull
$ git checkout ft-38-create-mystats-component-155907350
$ yarn start
```
- Go the `/my-activities` route when the app launches in the browser.
- Ensure you can view "my stats" as shown in the screenshot above.
> Resolves #38 - Create Stats component 155907350

- package.json
- src/assets/scss/Modal.scss
- src/assets/scss/PageHeader.scss
- src/assets/scss/reset.scss
- src/assets/scss/style.scss
- src/components/sidebar/FloatingActionButton.jsx
- src/containers/App.jsx
- src/containers/Modal.jsx
- tests/components/sidebar/FloatingActionButton.test.jsx
- tests/containers/App.test.jsx
- tests/containers/Modal.test.jsx
- yarn.lock
Add Modal component. When the FAB is clicked, the modal is visible.
- Clone this branch and checkout to it.
- Sign in to the app and click the FAB at the bottom right. A modal should appear.
> Resolves #156038187 - Create Modal component

- .circleci/config.yml
**What does this PR do?**
This P.R. fixes Continuous Deployment Pipeline for the application for staging
**Description of Task to be completed?**
The task involves automating the process of deploying the application currently being hosted on google cloud platform kubernetes engine. This involves changing the docker image that is running on the kubernetes cluster deployment. The task also solves a bug that was existent when a user was signing into the application. At the making of this P.R the backend application has not yet created a command to seed the database. This means the frontend app cannot yet start using the backend API. Currently it is using the mock server.
**How should this be manually tested?**
Merge the develop branch to the release branch. View the build on circle CI and …
> [#157836717] Fix Continuous Deployment Pipeline for the application for staging

- src/assets/scss/ErrorMessage.scss
- src/assets/scss/style.scss
- src/common/ErrorMessage.jsx
- src/containers/Redemptions.jsx
- src/fixtures/icons.js
- tests/common/ErrorMessage.test.jsx
- tests/containers/Redemptions.test.jsx
Creates a component to be used to display error messages.
`git clone` or `git pull` this repo or branch, `cd` into the project folder, run `yarn install` followed by `yarn start` to start the application. Login and navigate to `Redemptions`, if there's an error, you'll receive an error message with try again option.  
[158355400](https://www.pivotaltracker.com/story/show/158355400)
> #[158355400] Component to display errors in the application

- .circleci/config.yml
- config.js
- src/components/activities/ActivityCard.jsx
This P.R. resolves a bug where some links on the staging application were loading insecurely. It resolves the backend A.P.I URL from the initial mock server URL to the staging backend URL. It ensures that deployment to staging is made to the staging branch alone.
- When the buttons for societies are clicked, the page loads but the URL shows an insecure https path.
- The society links should be secured.
Visit the link http://staging-societies.andela.com and ensure that all links load over https.
[#158916136](https://www.pivotaltracker.com/story/show/158916136)
No.
> Resolves #158916136 Ensure all endpoints are being served under https

- src/assets/scss/MasonryLayout.scss
- src/assets/scss/Sidebar.scss
- src/components/sidebar/Sidebar.jsx
- src/containers/MasonryLayout.jsx
As a logged in user,
- Clicking the logo from anywhere should redirect me to the Home Page.
- When I am on the individual activities page, if there are no activities found "There are no activities at the moment." should be displayed on the page.
Once logged in as a user
- Click on the logo from anywhere in the page and ensure it redirects you to the Home Page.
- Navigate to individual activities page, ensure "There are no activities at the moment." is displayed 
on the page, if there are no activities found.
**When a user is logged in and no activities is found**
> #159128682 Fix found issues (V1)

- src/common/DateField.jsx
- src/common/Select.jsx
- src/common/SingleInput.jsx
- src/components/formErrors/FormError.jsx
- src/containers/forms/CommentsForm.jsx
- src/containers/forms/LogActivityForm.jsx
- src/containers/forms/RedeemPointsForm.jsx
- src/helpers/validate.js
- src/helpers/validateForm.js
- tests/components/formErrors/FormErrors.test.jsx
- tests/containers/forms/CommentsForm.test.jsx
- tests/containers/forms/LogActivityForm.test.jsx
- tests/containers/forms/RedeemPointsForm.test.jsx
- tests/helpers/validate.test.js
Number Inputs:
- A user could enter 0 or negative numbers
Dates
- A user could enter a date outside of the allowed current month limit
- Pulled in the npm package for juliancwirko:s-alert. https://www.npmjs.com/package/react-s-alert
- If you try to submit the log activity form with 0 or a negative value for points you should see the following error `Points has to be greater than zero`
- If you bypass the datepicker and type in a date which is greater than the current date, you should see the following error `Date entered is out of allowed range`
> [#159229919] refactor and enhance form field validation

- .github/PULL_REQUEST_TEMPLATE.md
- src/assets/scss/ActivityCard.scss
- src/components/activities/ActivityCard.jsx
- src/constants/clickAction.js
- src/constants/roles.js
- src/constants/statuses.js
- src/containers/Home.jsx
- src/containers/Redemptions.jsx
- src/helpers/pageInfo.js
- tests/components/activities/ActivityCard.test.jsx
- tests/containers/Redemptions.test.jsx
- Finance member should be able to log in 
- Once logged in, finance member should be able to see the approved request
- Finance member should be able to complete the request and also see the center of the redemption
- As a user logged in as a member of the finance department, when a redemption request is approved I should get an email notification with a link to view more details about the redemption. Notifications module
- The notification module is not yet done from the backend and there will therefore be a different bug for the same
- Also to be **Noted**, I added a pull request template for consistency
- N/A
> Finance status update redemption

- src/containers/MyActivities.jsx
- src/helpers/statsGenerator.js
Displays point earned on MyActivities page as per total points of approved activities.
The value displayed for points earned on MyActivities page should correspond to the total points of approved activities.
[159519054](https://www.pivotaltracker.com/story/show/159519054)
N/A
> Fixes points earned on My Activities page

- .github/PULL_REQUEST_TEMPLATE.md
- src/assets/scss/PageHeader.scss
- src/components/header/PageHeader.jsx
- Fixes dropdown menu:
- Styling
- Click Actions of status
- Dropdown toggle open and clos
- pull request template
- Fix Dropdown Menu
- Current Dropdown malfunctioning
- The use of the onKeydown event handler is because of the following
> Fix Dropdown Menu

- src/containers/MyActivities.jsx
Modifies the stats title on my activities page
Display a descriptive name for the stats title.
[159799750](https://www.pivotaltracker.com/story/show/159799750)
N/A
> modify stats title

- src/assets/scss/PageHeader.scss
- src/assets/scss/_vars.scss
- src/common/Button.jsx
- src/components/header/PageHeader.jsx
- src/containers/Categories.jsx
- src/containers/Redemptions.jsx
- src/containers/VerifyActivities.jsx
- tests/common/Button.test.jsx
- tests/components/header/PageHeader.test.jsx
Grey's out approve  button if there are no tasks to be approved.
Grey out approve selected button if no task is found on verify activities page.
N/A
[159804941)](https://www.pivotaltracker.com/story/show/159804941)
N/A
> grey out button if verify activity is not found

- src/components/header/Header.jsx
- Removes the notifications from the Header
- Removes the notifications icon from the Header
- Task is incomplete on the backend from MVP
- N/A
-None
> Remove notifications from header

- .eslintignore
- src/fixtures/activities.js
- src/fixtures/activity.js
- tests/actions/createCategoryActions.test.js
- tests/actions/redeemPointsActions.test.js
- Fix Eslint errors
- FIx all eslint errors 
- None
- None
- None
- N/A
> Fix Eslint errors

- src/assets/scss/ActivityCard.scss
- src/assets/scss/CategoryCard.scss
- src/assets/scss/_mixins.scss
- src/assets/scss/_vars.scss
- Fixes activity and category card styling
- Fix activity and category card styling
- Cards had a plain look and din't pop as would have been expected
- N/A
- None
Go to this link for a screencast of the same => https://goo.gl/yqve7V
> Fix activity and category card styling

- package.json
- src/actions/verifyActivityActions.js
- src/components/activities/ActivityCard.jsx
- src/containers/Categories.jsx
- src/containers/Home.jsx
- src/containers/MyActivities.jsx
- src/containers/Page.jsx
- src/containers/Redemptions.jsx
- src/containers/VerifyActivities.jsx
- src/containers/forms/LogActivityForm.jsx
- tests/actions/verifyActivityActions.test.js
- tests/containers/Categories.test.jsx
- tests/containers/Home.test.jsx
- tests/containers/MyActivities.test.jsx
- tests/containers/Redemptions.test.jsx
- tests/containers/VerifyActivities.test.jsx
- yarn.lock
Returns the logged in user to the page he/she was upon refreshing the page. Also, refactors URL used to approve logged activities.
* Set the user's current location in `sessionStorage` in all containers i.e. `MyActivities`, `Verify Activities`, `Categories`.
* Refactor the URL used to approve logged activities.
The current location had to be stored somewhere out of React context since on refreshing the webpage, state data is lost. 
[160092898](https://www.pivotaltracker.com/story/show/160092898)
https://www.useloom.com/share/ca68301521fd46738873c686339ed63f
> Bg 160092898 fix redirection on reloading a page

- src/assets/scss/Stats.scss
- tests/containers/VerifyActivities.test.jsx
Fixes the display of Sparks Logo in the Society Stats.
Enable that `Sparks Logo` is seen in the stats components.
N/A
> fix sparks logo

- src/containers/VerifyActivities.jsx
Fixes the bug to enable the society secretary to approve an activity
Pass down `pending` status to `verifyActivity` action.
[160376833](https://www.pivotaltracker.com/story/show/160376833)
https://www.useloom.com/share/d3aabdc8f28c4020b8ebef16258f6588
> Fix bug to enable society secretary to approve an activity

- Makefile
- README.md
- config.js
- docker/dev/docker-compose.yml
- docker/dev/sandbox.md
- package.json
- scripts/sandbox.sh
- The developers need a local environment that mirrors staging.
- I created part of a docker replica of the infrastructure that is on staging.
e.g.
```
mkdir soc-app
cd soc-app
git clone -b ft-sandbox-159817309 https://github.com/WinstonKamau/andela-societies-backend
git clone -b ft-sandbox-159817309 https://github.com/WinstonKamau/andela-societies-frontend
```
Ensure port 4021, 4022 and 4023 are not running on your machine.
Change directory to the backend
```
cd ../andela-societies-backend
```
Ensure you have **ALL** your environment variables set in the src/.env file. 
```
PRIVATE_KEY_TEST=""
PUBLIC_KEY_TEST=""
PUBLIC_KEY=""
DEV_DATABASE=""
DATABASE_URL=""
APP_SETTINGS=""
ANDELA_API_URL=
DEV_TOKEN=
MAIL_GUN_URL=
MAIL_GUN_API_KEY=
MAIL_GUN_TEST="'Insert MailGun test thingy here'" …
```
> #159817309 Create a sandbox environment for the developers

- src/containers/VerifyActivities.jsx
- src/fixtures/store.js
- src/reducers/allActivitiesReducer.js
- src/reducers/initialState.js
- tests/components/header/Header.test.jsx
- tests/containers/Redemptions.test.jsx
- tests/containers/VerifyActivities.test.jsx
- tests/reducers/allActivitiesReducer.test.js
Displays error message using the snack bar when approving more than 20 logged activities.
* Add a message object to `allActivities` state
* Mapped `allActivities.message` state to props
* Mapped `message` prop to state in VerifyActivities component
* Updated `allActivitiesReducer` tests
[160491066](https://www.pivotaltracker.com/story/show/160491066)
> Display an error message when approving more than 20 activities

- src/containers/Redemptions.jsx
- src/containers/VerifyActivities.jsx
- tests/containers/VerifyActivities.test.jsx
Remove comment section from verify activity and redemption pages.
Remove comment section from everywhere it's been used in FEND.
N/A
N/A
> (CHORE) Remove comment section from verify activity and redemption pages.

- src/actions/verifyActivityActions.js
- src/containers/forms/CreateCategoryForm.jsx
- tests/actions/verifyActivityActions.test.js
- tests/containers/VerifyActivities.test.jsx
Update Reject category endpoint
Update the endpoints to the right endpoint
From `https://api-staging-societies.andela.com/api/v1/logged-activities/review/` to `https://api-staging-societies.andela.com/api/v1/logged-activities/reject/`
N/A
N/A
N/A
> Change Endpoint for Redemption request

- src/actions/redeemPointsAction.js
- src/containers/VerifyActivities.jsx
> add pagination in redemption

- README.md
- src/assets/scss/SignIn.scss
- tests/containers/forms/CommentsForm.test.jsx
- Updates the README file with relevant information.
- Updates the README file with relevant links and images.
- Updates the SignIn page icons with the `Andelan` blue color.
- Update the README file with the relevant information so as to give a new person in the project in-depth information.
- The README had information about setting up but it was not detailed enough.
N/A
N/A
> ch(README.md): update the README file

- src/assets/scss/ActivityCard.scss
Changes the styling of the ActivityCard component to give a more aesthetic look
- Provide a fixed width and height for the ActivityCard Component.
> #161249746 Fix ActivityCard dimensions.

- src/containers/Society.jsx
Implements filtering for activities on the Society View based on status.
[161249558](https://www.pivotaltracker.com/story/show/161249558)
> 161249558 Implement filtering of activities based on status.

- src/containers/Home.jsx
- src/containers/Page.jsx
- src/helpers/authentication.js
Resolves the bug experienced when an Andean who is not a fellow sign in.
- Remove `isFellow(tokenInfo) === false ` condition in Page component.
- Remove the action call to `fetchUserProfile ` in Home component as it is called in Page component
> Bug fix for Andelan sign in error

- .gitignore
- docker/dev/Dockerfile
- docker/dev/docker-compose.yml
- docker/dev/sandbox.md
- sandserver
This Pull Request implements logging on the frontend application.
The task involves installing a package from npm store called [morgan](https://www.npmjs.com/package/morgan). The package is a HTTP request logger middleware for node.js. The logger is directed to log to a file on the sandbox to enable use of volumes. It maintains its default logging on the GCP infrastructure.
None
https://www.pivotaltracker.com/story/show/162052401
A view of logs from the sandbox 
A view of logs on GCP
> #162052401 Implement Logging on Kubernetes and the Sandbox

- .circleci/config.yml
- config.js
- scripts/deploy.sh
This P.R creates a CI/CD pipeline for the MVP 2 changes that the team will be working on.
* Create a CI/CD pipeline for a `design` branch that will deploy to GCP
* The resources for the design branch have been deployed to the Kubernetes staging cluster.
https://www.pivotaltracker.com/story/show/162496788
> #162496788 Create a CI/CD pipeline for the MVP2 changes

- README.md
This P.R renames the status badges for the repository to point to the new organization.
The task involved migrating the repository to the new organization and ensuring that developers have a smooth transition.
https://www.pivotaltracker.com/story/show/162779200
> #162779200 Rename the badges to point to the new repository

- .coveralls.yml
- README.md
This P.R fixes the CI on the MVP 2
* Update Circle CI and coveralls badge to point to the correct repository.
* Add branch protection rules for the develop-v2 branch
None
https://www.pivotaltracker.com/story/show/163145741
None.
Old view
Updated view
Branch protection rules
> #163145741 Fix CI badges.

- .circleci/config.yml
- config.js
- scripts/deploy.sh
This PR removes deployment pipeline for the MVP 2 on the MVP 1 code.
Remove code script for deploying the MVP2.
Remove the design environment from the Node environment for docker image builds.
N/A
https://www.pivotaltracker.com/story/show/163449835
N/A
N/A
> #163449835 Remove Deployment pipeline for MVP2 on the develop branch

- src/app/Authentication/components/AuthenticateRoute.js
- src/app/Dashboard/components/DashboardContainer.js
- src/app/Dashboard/components/MyActivitiesComponent.js
- src/app/Dashboard/components/TruncateDescriptionContainer.js
- src/app/Dashboard/components/index.js
- src/app/Dashboard/components/tests/DashboardContainer.test.js
- src/app/Dashboard/components/tests/TruncateDescriptionContainer.test.js
- src/app/Login/components/LoginContainer.js
- src/app/Login/components/index.js
- src/app/Login/components/tests/LoginContainer.test.js
- src/app/common/components/NavbarContainer.js
- src/app/common/components/index.js
- src/app/common/components/tests/NavbarContainer.test.js
- src/routes.js
Renames stateful components to have `Container` suffix
Renamed the following components: 
*  DashboardComponent 
* TruncateDescriptionComponent
* LoginComponent
* NavbarComponent
> Rename stateful components to have Container suffix

- src/app/Authentication/components/AuthenticateRoute.js
- src/app/Dashboard/components/DashboardContainer.js
- src/app/Dashboard/styles/societyStats.scss
- src/app/common/components/NavbarContainer.js
- src/app/common/components/ProfileContainer.js
- src/app/common/components/tests/ProfileContainer.test.js
- src/app/common/styles/index.scss
- src/app/common/styles/logo.scss
- src/app/common/styles/navbar.scss
- src/app/common/styles/profile.scss
- src/app/utils/tests/tokenIsValid.test.js
- src/app/utils/tokenIsValid.js
- src/routes.js
- src/styles/_vars.scss
Adds the profile section with a dropdown menu with logout and profile menu items.
* Add ProfileComponent
* Add a dropdown menu with profile and logout menu options
* Add tests
[164241282](https://www.pivotaltracker.com/story/show/164241282)
This branch has work that the PR `Display redesigned my logged activities ` delivers.
> #164241282 Display user profile

- .circleci/config.yml
- scripts/deploy.sh
- scripts/slack_notification.sh
Creates a pipeline for deploying the frontend master-V2 branch
Create a pipeline that deploys master-v2 to the production-v2-frontend workload
N/A
https://www.pivotaltracker.com/story/show/164102566
N/A
N/A
> #164102566 MVP2 production pipeline

- src/app/Dashboard/components/DashboardContainer.js
- src/app/Dashboard/operations/actions.js
- src/app/Dashboard/operations/dashboard.data.js
- src/app/Dashboard/operations/reducer.js
- src/app/Dashboard/operations/tests/fixtures.js
- src/app/Dashboard/operations/tests/reducer.test.js
- src/reducers/initialState.js
Adds a user's `D level`
[#164860619](https://www.pivotaltracker.com/story/show/164860619)
> #164860619 Add user's D-level

- src/app/Dashboard/styles/dashboard.scss
- src/app/Redemptions/components/RedemptionsComponent.js
- src/app/Redemptions/components/RedemptionsContainer.js
- src/app/Redemptions/components/index.js
- src/app/Redemptions/components/tests/RedemptionsComponent.test.js
- src/app/Redemptions/components/tests/RedemptionsContainer.test.js
- src/app/Redemptions/components/tests/fixtures.js
- src/app/Sidebar/components/SidebarContainer.js
- src/app/Sidebar/components/tests/SidebarContainer.test.js
- src/routes.js
Add Redemptions page
[164830528](https://www.pivotaltracker.com/story/show/164830528)
> #164830528 Display redemptions page

- src/app/ApproveActivities/components/ApproveActivitiesComponent.js
- src/app/ApproveActivities/components/ApproveActivitiesContainer.js
- src/app/ApproveActivities/components/index.js
- src/app/ApproveActivities/components/tests/ApproveActivitiesComponent.test.js
- src/app/ApproveActivities/components/tests/ApproveActivitiesContainer.test.js
- src/app/Sidebar/components/SidebarContainer.js
- src/app/Sidebar/components/tests/SidebarContainer.test.js
- src/app/Sidebar/styles/sidebar.scss
- src/routes.js
Enables a user i.e. success team/member, to view activities to approve/reject.
> Display activities to approve/reject

- package.json
- src/app/ApproveActivities/components/ApproveActivitiesComponent.js
- src/app/ApproveActivities/components/ApproveActivitiesContainer.js
- src/app/ApproveActivities/components/tests/ApproveActivitiesContainer.test.js
- src/app/ApproveBudget/components/ApproveBudgetContainer.js
- src/app/ApproveBudget/components/tests/ApproveBudgetContainer.test.js
- src/app/Dashboard/components/DashboardContainer.js
- src/app/Dashboard/components/tests/DashboardContainer.test.js
- src/app/Dashboard/styles/dashboard.scss
- src/app/Societies/components/SocietiesContainer.js
- src/app/Societies/components/tests/SocietiesContainer.test.js
- src/app/VerifyActivities/components/VerifyActivitiesContainer.js
- src/app/VerifyActivities/components/tests/VerifyActivitiesContainer.test.js
- src/sagas/index.js
Demo [Link](https://streamable.com/wgyir)
> Add pagination

- src/app/Dashboard/components/DashboardContainer.js
- src/app/Sidebar/components/SidebarContainer.js
- src/app/Sidebar/components/tests/SidebarContainer.test.js
- src/app/Sidebar/styles/sidebar.scss
- src/app/common/components/ProfileContainer.js
- src/app/common/styles/profile.scss
- src/sagas/index.js
Fixes the dashboard icon alignment disables footer settings and profile dropdown option
> Fix dashboard icon alignment, disable footer settings and profile dropdown option

- src/app/Login/components/LoginContainer.js
- src/app/common/components/ProfileContainer.js
- src/sagas/index.js
Removes the blue login background and adds `watchCreateRedemptionReq` import.
> Removes the blue login background

- config.js
- src/app/ApproveActivities/components/ApproveActivitiesContainer.js
- src/app/ApproveBudget/components/ApproveBudgetContainer.js
- src/app/Dashboard/components/DashboardContainer.js
- src/app/Societies/components/SocietiesContainer.js
- src/app/VerifyActivities/components/VerifyActivitiesContainer.js
Fixes the API Base url bug and when Pagination display
- The pagination buttons should only be displayed when the items being mapped are greater than 6.
- Fix the Production API base url to use the as-bend staging url
> Fix API Base url bug and Pagination display

- src/app/Societies/components/SocietyActivitiesComponent.js
- src/app/Societies/operations/societies.data.js
- src/app/Societies/operations/tests/societies.test.js
- src/app/VerifyActivities/components/VerifyActivitiesComponent.js
- src/app/VerifyActivities/components/VerifyActivitiesContainer.js
- src/app/common/components/ActionsComponent.js
Fix redemption date and verify status sent errors encountered while using the staging environment
- fix redemption date error
- fix activity status sent while verifying by society secretary
> Fix redemption date and verify status sent errors

- .circleci/config.yml
> remove require

- src/app/Societies/styles/societies.scss
> remove background colour
